################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/activations.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/activations_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/add_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/add_n.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/arg_min_max.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/assign_variable.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/batch_matmul_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/broadcast_args.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/broadcast_to.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/call_once.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/cast.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/ceil.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/comparisons.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/concatenation.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/conv_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/cumsum.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/decompress.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/decompress_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/depth_to_space.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/dequantize.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/dequantize_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/div.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/elementwise.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/elu.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/embedding_lookup.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/exp.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/expand_dims.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/fill.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor_div.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor_mod.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/gather.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/gather_nd.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/hard_swish.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/if.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/kernel_util.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/l2norm.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/leaky_relu.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/log_softmax.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logical.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logical_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logistic.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logistic_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/lstm_eval.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/mirror_pad.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/mul_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/neg.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pack.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pad.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pooling_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/prelu.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/prelu_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/quantize.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/quantize_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/read_variable.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reduce.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reduce_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reshape.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reshape_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/round.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/select.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/shape.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/slice.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/softmax_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/space_to_depth.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/split.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/split_v.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/squared_difference.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/squeeze.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/strided_slice.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/strided_slice_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/sub.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/sub_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/svdf_common.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/tanh.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/transpose.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/unpack.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/var_handle.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/while.cc \
../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/zeros_like.cc 

CREF += \
ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640.cref 

CC_DEPS += \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/activations.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/activations_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/add_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/add_n.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/arg_min_max.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/assign_variable.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/batch_matmul_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/broadcast_args.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/broadcast_to.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/call_once.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/cast.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/ceil.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/comparisons.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/concatenation.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/conv_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/cumsum.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/decompress.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/decompress_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/depth_to_space.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/dequantize.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/dequantize_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/detection_postprocess.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/div.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/elementwise.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/elu.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/embedding_lookup.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/exp.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/expand_dims.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/fill.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor_div.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor_mod.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/fully_connected_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/gather.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/gather_nd.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/hard_swish.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/hard_swish_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/if.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/kernel_util.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/l2norm.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/leaky_relu.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/log_softmax.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logical.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logical_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logistic.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logistic_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/lstm_eval.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/lstm_eval_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/mirror_pad.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/mul_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/neg.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pack.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pad.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pooling_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/prelu.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/prelu_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/quantize.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/quantize_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/read_variable.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reduce.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reduce_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reshape.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reshape_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/resize_bilinear.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/round.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/select.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/shape.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/slice.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/softmax_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/space_to_depth.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/split.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/split_v.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/squared_difference.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/squeeze.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/strided_slice.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/strided_slice_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/sub.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/sub_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/svdf_common.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/tanh.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/transpose.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/unpack.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/var_handle.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/while.d \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/activations.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/activations_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/add_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/add_n.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/arg_min_max.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/assign_variable.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/batch_matmul_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/broadcast_args.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/broadcast_to.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/call_once.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/cast.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/ceil.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/comparisons.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/concatenation.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/conv_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/cumsum.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/decompress.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/decompress_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/depth_to_space.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/dequantize.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/dequantize_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/detection_postprocess.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/div.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/elementwise.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/elu.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/embedding_lookup.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/exp.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/expand_dims.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/fill.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor_div.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/floor_mod.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/fully_connected_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/gather.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/gather_nd.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/hard_swish.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/hard_swish_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/if.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/kernel_util.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/l2norm.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/leaky_relu.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/log_softmax.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logical.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logical_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logistic.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/logistic_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/lstm_eval.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/lstm_eval_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/mirror_pad.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/mul_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/neg.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pack.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pad.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/pooling_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/prelu.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/prelu_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/quantize.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/quantize_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/read_variable.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reduce.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reduce_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reshape.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/reshape_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/resize_bilinear.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/round.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/select.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/shape.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/slice.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/softmax_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/space_to_depth.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/split.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/split_v.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/squared_difference.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/squeeze.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/strided_slice.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/strided_slice_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/sub.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/sub_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/svdf_common.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/tanh.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/transpose.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/unpack.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/var_handle.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/while.o \
./ra/npu/tflite-micro/tensorflow/lite/micro/kernels/zeros_like.o 

MAP += \
ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640.map 


# Each subdirectory must supply rules for building sources it contributes
ra/npu/tflite-micro/tensorflow/lite/micro/kernels/%.o: ../ra/npu/tflite-micro/tensorflow/lite/micro/kernels/%.cc
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=cortex-m85 -mthumb -mlittle-endian -mfloat-abi=hard -Os -ffunction-sections -fdata-sections -fno-strict-aliasing -fmessage-length=0 -funsigned-char -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Waggregate-return -Wno-parentheses-equality -Wfloat-equal -g3 -std=c++17 -flax-vector-conversions -fshort-enums -fno-unroll-loops -fno-rtti -fno-exceptions -w -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src" -I"." -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/inc" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/inc/api" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/inc/instances" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/src/rm_freertos_port" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/aws/FreeRTOS/FreeRTOS/Source/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/arm/CMSIS_6/CMSIS/Core/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra_gen" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra_cfg/fsp_cfg/bsp" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra_cfg/fsp_cfg" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra_cfg/aws" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/src/rm_ethosu" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/tes/dave2d/inc" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/arm/CMSIS-NN/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/arm/CMSIS-NN" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/flatbuffers/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/arm/CMSIS-DSP/PrivateInclude" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/arm/CMSIS-DSP/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/layer_by_layer_profiler/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/ethosu_monitor/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/ethosu_profiler/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/ethos-u-core-driver/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/ruy" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/gemmlowp" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/tflite-micro" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/crc/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/arm_profiler/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/arm/CMSIS-View/EventRecorder/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/arm/CMSIS-View/EventRecorder/Config" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/ai_application" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/ai_application/common" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/ai_application/ruhmi_conversion_results" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/camera_layer" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/display_layer" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/time_counter" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/console_output" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/src/external_memory" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/src/r_mipi_csi" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/src/r_vin" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_hand_landmarkmodel_gesture_recognition_camera_LCD_FSP640/ra/fsp/src/r_drw" -D_RENESAS_RA_ -D_RA_CORE=CPU0 -DTF_LITE_STATIC_MEMORY -D_RA_ORDINAL=1 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -x c++ "$<" -c -o "$@")
	@clang++ --target=arm-none-eabi @"$@.in"

