################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.c 

CREF += \
ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640.cref 

C_DEPS += \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.o 

MAP += \
ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640.map 


# Each subdirectory must supply rules for building sources it contributes
ra/arm/CMSIS-DSP/Source/StatisticsFunctions/%.o: ../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=cortex-m85 -mthumb -mlittle-endian -mfloat-abi=hard -Os -ffunction-sections -fdata-sections -fno-strict-aliasing -fmessage-length=0 -funsigned-char -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Waggregate-return -Wno-parentheses-equality -Wfloat-equal -g3 -std=c99 -flax-vector-conversions -fshort-enums -fno-unroll-loops -w -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src" -I"." -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/inc" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/inc/api" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/inc/instances" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/src/rm_freertos_port" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/aws/FreeRTOS/FreeRTOS/Source/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/arm/CMSIS_6/CMSIS/Core/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra_gen" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra_cfg/fsp_cfg/bsp" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra_cfg/fsp_cfg" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra_cfg/aws" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/src/rm_ethosu" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/tes/dave2d/inc" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/arm/CMSIS-NN/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/arm/CMSIS-NN" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/flatbuffers/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/arm/CMSIS-DSP/PrivateInclude" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/arm/CMSIS-DSP/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/layer_by_layer_profiler/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/ethosu_monitor/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/ethosu_profiler/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/ethos-u-core-driver/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/ruy" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/gemmlowp" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/tflite-micro" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/crc/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/npu/ethos-u-core-software/lib/arm_profiler/include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/arm/CMSIS-View/EventRecorder/Include" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/arm/CMSIS-View/EventRecorder/Config" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/ai_application" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/ai_application/common" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/ai_application/ruhmi_conversion_results" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/camera_layer" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/display_layer" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/time_counter" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/console_output" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/src/external_memory" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/src/r_mipi_csi" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/src/r_vin" -I"/home/eldorado/e2_studio/workspace_6.4/ek_ra8p1_vision_palm_detection_model_camera_LCD_FSP640/ra/fsp/src/r_drw" -D_RENESAS_RA_ -D_RA_CORE=CPU0 -D_RA_ORDINAL=1 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -x c "$<" -c -o "$@")
	@clang --target=arm-none-eabi @"$@.in"

