################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_UPPER_SRCS := 
ASM_UPPER_SRCS := 
C++M_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
LINKER_SCRIPT := 
SX_SRCS := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
X_SRCS := 
SRC_SRCS := 
X_UPPER_SRCS := 
CCM_UPPER_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
CXXM_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C++M_UPPER_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CC_UPPER_DEPS := 
C++M_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
CREF := 
OBJCOPY := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
CXX_DEPS := 
SX_UPPER_DEPS := 
CXX_UPPER_DEPS := 
JMP_DEPS := 
CCM_DEPS := 
P_UPPER_DEPS := 
CXXM_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
CCM_UPPER_DEPS := 
SRC_DEPS := 
CC_DEPS := 
PP_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
ASM_DEPS := 
MAP := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/arm/CMSIS-DSP/Source/BasicMathFunctions \
ra/arm/CMSIS-DSP/Source/BayesFunctions \
ra/arm/CMSIS-DSP/Source/CommonTables \
ra/arm/CMSIS-DSP/Source/ComplexMathFunctions \
ra/arm/CMSIS-DSP/Source/ControllerFunctions \
ra/arm/CMSIS-DSP/Source/DistanceFunctions \
ra/arm/CMSIS-DSP/Source/FastMathFunctions \
ra/arm/CMSIS-DSP/Source/FilteringFunctions \
ra/arm/CMSIS-DSP/Source/InterpolationFunctions \
ra/arm/CMSIS-DSP/Source \
ra/arm/CMSIS-DSP/Source/MatrixFunctions \
ra/arm/CMSIS-DSP/Source/QuaternionMathFunctions \
ra/arm/CMSIS-DSP/Source/SVMFunctions \
ra/arm/CMSIS-DSP/Source/StatisticsFunctions \
ra/arm/CMSIS-DSP/Source/SupportFunctions \
ra/arm/CMSIS-DSP/Source/TransformFunctions \
ra/arm/CMSIS-DSP/Source/WindowFunctions \
ra/arm/CMSIS-NN/Source/ActivationFunctions \
ra/arm/CMSIS-NN/Source/BasicMathFunctions \
ra/arm/CMSIS-NN/Source/ConcatenationFunctions \
ra/arm/CMSIS-NN/Source/ConvolutionFunctions \
ra/arm/CMSIS-NN/Source/FullyConnectedFunctions \
ra/arm/CMSIS-NN/Source/LSTMFunctions \
ra/arm/CMSIS-NN/Source/NNSupportFunctions \
ra/arm/CMSIS-NN/Source/PadFunctions \
ra/arm/CMSIS-NN/Source/PoolingFunctions \
ra/arm/CMSIS-NN/Source/ReshapeFunctions \
ra/arm/CMSIS-NN/Source/SVDFunctions \
ra/arm/CMSIS-NN/Source/SoftmaxFunctions \
ra/arm/CMSIS-NN/Source/TransposeFunctions \
ra/arm/CMSIS-View/EventRecorder/Source \
ra/arm/CMSIS_6 \
ra/aws/FreeRTOS/FreeRTOS/Source \
ra/aws/FreeRTOS/FreeRTOS/Source/portable/MemMang \
ra/board/ra8p1_ek \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra8p1 \
ra/fsp/src/r_dmac \
ra/fsp/src/r_drw \
ra/fsp/src/r_glcdc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_ospi_b \
ra/fsp/src/r_sci_b_uart \
ra/fsp/src/rm_ethosu \
ra/fsp/src/rm_freertos_port \
ra/npu/ethos-u-core-driver/src \
ra/npu/ethos-u-core-software/lib/arm_profiler/src \
ra/npu/ethos-u-core-software/lib/ethosu_monitor/src \
ra/npu/ethos-u-core-software/lib/ethosu_profiler/src \
ra/npu/ethos-u-core-software/lib/layer_by_layer_profiler/src \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/core/api \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/core/c \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/kernels/internal \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/schema \
ra/npu/tflite-micro/tensorflow/lite \
ra/npu/tflite-micro/tensorflow/lite/c \
ra/npu/tflite-micro/tensorflow/lite/core \
ra/npu/tflite-micro/tensorflow/lite/core/api \
ra/npu/tflite-micro/tensorflow/lite/core/c \
ra/npu/tflite-micro/tensorflow/lite/kernels \
ra/npu/tflite-micro/tensorflow/lite/kernels/internal \
ra/npu/tflite-micro/tensorflow/lite/kernels/internal/reference \
ra/npu/tflite-micro/tensorflow/lite/micro/arena_allocator \
ra/npu/tflite-micro/tensorflow/lite/micro/cortex_m_generic \
ra/npu/tflite-micro/tensorflow/lite/micro \
ra/npu/tflite-micro/tensorflow/lite/micro/kernels \
ra/npu/tflite-micro/tensorflow/lite/micro/kernels/cmsis_nn \
ra/npu/tflite-micro/tensorflow/lite/micro/kernels/ethos_u \
ra/npu/tflite-micro/tensorflow/lite/micro/memory_planner \
ra/npu/tflite-micro/tensorflow/lite/micro/tflite_bridge \
ra/npu/tflite-micro/tensorflow/lite/schema \
ra/tes/dave2d/src \
ra_gen \
src/ai_application/common \
src/ai_application \
src/ai_application/face_detection \
src/ai_application/face_detection/mera \
src \
src/camera_layer \
src/console_output/SEGGER_RTT \
src/console_output \
src/display_layer \
src/external_memory \
src/fsp_custom \
src/fsp_custom/r_mipi_phy \
src/time_counter \

