################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.c 

CREF += \
ek_ra8p1_vision_image_classification_mobilenet_v1.cref 

C_DEPS += \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d 

OBJS += \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o 

MAP += \
ek_ra8p1_vision_image_classification_mobilenet_v1.map 


# Each subdirectory must supply rules for building sources it contributes
ra/arm/CMSIS-DSP/Source/FilteringFunctions/%.o: ../ra/arm/CMSIS-DSP/Source/FilteringFunctions/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=cortex-m85 -mthumb -mlittle-endian -mfloat-abi=hard -O2 -ffunction-sections -fdata-sections -fno-strict-aliasing -fmessage-length=0 -funsigned-char -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Waggregate-return -Wno-parentheses-equality -Wfloat-equal -g3 -std=c99 -flax-vector-conversions -fshort-enums -fno-unroll-loops -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src" -I"." -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\inc" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\inc\\api" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\inc\\instances" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\src\\rm_freertos_port" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\aws\\FreeRTOS\\FreeRTOS\\Source\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\arm\\CMSIS_6\\CMSIS\\Core\\Include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra_gen" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra_cfg\\fsp_cfg\\bsp" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra_cfg\\fsp_cfg" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra_cfg\\aws" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\src\\rm_ethosu" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\tes\\dave2d\\inc" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\arm\\CMSIS-NN\\Include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\arm\\CMSIS-NN" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\flatbuffers\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\arm\\CMSIS-DSP\\PrivateInclude" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\arm\\CMSIS-DSP\\Include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\ethos-u-core-software\\lib\\layer_by_layer_profiler\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_monitor\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_profiler\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\ethos-u-core-driver\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\ruy" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\gemmlowp" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\tflite-micro" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\ethos-u-core-software\\lib\\crc\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\npu\\ethos-u-core-software\\lib\\arm_profiler\\include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\arm\\CMSIS-View\\EventRecorder\\Include" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\arm\\CMSIS-View\\EventRecorder\\Config" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\ai_application" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\ai_application\\common" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\ai_application\\image_classification" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\ai_application\\ruhmi_conversion_results" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\camera_layer" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\display_layer" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\time_counter" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\console_output" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\src\\external_memory" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\src\\r_mipi_csi" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\src\\r_vin" -I"C:\\Users\\a5033228\\e2_studio\\workspace_app_test\\ek_ra8p1_vision_image_classification_mobilenet_v1\\ra\\fsp\\src\\r_drw" -D_RENESAS_RA_ -D_RA_CORE=CPU0 -D_RA_ORDINAL=1 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -x c "$<" -c -o "$@")
	@clang --target=arm-none-eabi @"$@.in"

